//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation
import Prch

/** A search result contains information about a YouTube video, channel, or playlist that matches the search parameters specified in an API request. While a search result points to a uniquely identifiable resource, like a video, it does not have its own persistent data. */
public struct SearchResult: Model {

    /** Etag of this resource. */
    public var etag: String?

    /** The id object contains information that can be used to uniquely identify the resource that matches the search request. */
    public var id: ResourceId?

    /** Identifies what kind of resource this is. Value: the fixed string "youtube#searchResult". */
    public var kind: String?

    /** The snippet object contains basic details about a search result, such as its title or description. For example, if the search result is a video, then the title will be the video's title and the description will be the video's description. */
    public var snippet: SearchResultSnippet?

    public init(etag: String? = nil, id: ResourceId? = nil, kind: String? = nil, snippet: SearchResultSnippet? = nil) {
        self.etag = etag
        self.id = id
        self.kind = kind
        self.snippet = snippet
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        etag = try container.decodeIfPresent("etag")
        id = try container.decodeIfPresent("id")
        kind = try container.decodeIfPresent("kind")
        snippet = try container.decodeIfPresent("snippet")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(etag, forKey: "etag")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(kind, forKey: "kind")
        try container.encodeIfPresent(snippet, forKey: "snippet")
    }

}
