//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation
import Prch

public struct TestItemTestItemSnippet: Model {

    public init() {
    }

    public init(from decoder: Decoder) throws {
    }

    public func encode(to encoder: Encoder) throws {
    }

}
