//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation
import Prch

/** Stub token pagination template to suppress results. */
public struct TokenPagination: Model {

    public init() {
    }

    public init(from decoder: Decoder) throws {
    }

    public func encode(to encoder: Encoder) throws {
    }

}
