#if !canImport(ObjectiveC)
  import XCTest

  extension PlaylistTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PlaylistTests = [
      ("testVideos", testVideos)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(PlaylistTests.__allTests__PlaylistTests)
    ]
  }
#endif
