//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

/** Data format for response. */
public enum Alt: String, Codable, Equatable, CaseIterable {
    case json = "json"
    case media = "media"
    case proto = "proto"
}
