//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation
import Prch

extension Channels {

    /** Updates an existing resource. */
    public enum YoutubeChannelsUpdate {

        public static let service = APIService<Response>(id: "youtube.channels.update", tag: "channels", method: "PUT", path: "/youtube/v3/channels", hasBody: true, securityRequirements: [SecurityRequirement(type: "Oauth2", scopes: ["https://www.googleapis.com/auth/youtube"]), SecurityRequirement(type: "Oauth2", scopes: ["https://www.googleapis.com/auth/youtube.force-ssl"]), SecurityRequirement(type: "Oauth2", scopes: ["https://www.googleapis.com/auth/youtubepartner"])])

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** V1 error format. */
                public var dollarXgafv: Xgafv?

                /** OAuth access token. */
                public var accessToken: String?

                /** Data format for response. */
                public var alt: Alt?

                /** JSONP */
                public var callback: String?

                /** Selector specifying which fields to include in a partial response. */
                public var fields: String?

                /** API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token. */
                public var key: String?

                /** OAuth 2.0 token for the current user. */
                public var oauthToken: String?

                /** Returns response with indentations and line breaks. */
                public var prettyPrint: Bool?

                /** Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. */
                public var quotaUser: String?

                /** Upload protocol for media (e.g. "raw", "multipart"). */
                public var uploadProtocol: String?

                /** Legacy upload protocol for media (e.g. "media", "multipart"). */
                public var uploadType: String?

                /** The *part* parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include. The API currently only allows the parameter value to be set to either brandingSettings or invideoPromotion. (You cannot update both of those parts with a single request.) Note that this method overrides the existing values for all of the mutable properties that are contained in any parts that the parameter value specifies. */
                public var part: [String]

                /** The *onBehalfOfContentOwner* parameter indicates that the authenticated user is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their video and channel data, without having to provide authentication credentials for each individual channel. The actual CMS account that the user authenticates with needs to be linked to the specified YouTube content owner. */
                public var onBehalfOfContentOwner: String?

                public init(dollarXgafv: Xgafv? = nil, accessToken: String? = nil, alt: Alt? = nil, callback: String? = nil, fields: String? = nil, key: String? = nil, oauthToken: String? = nil, prettyPrint: Bool? = nil, quotaUser: String? = nil, uploadProtocol: String? = nil, uploadType: String? = nil, part: [String], onBehalfOfContentOwner: String? = nil) {
                    self.dollarXgafv = dollarXgafv
                    self.accessToken = accessToken
                    self.alt = alt
                    self.callback = callback
                    self.fields = fields
                    self.key = key
                    self.oauthToken = oauthToken
                    self.prettyPrint = prettyPrint
                    self.quotaUser = quotaUser
                    self.uploadProtocol = uploadProtocol
                    self.uploadType = uploadType
                    self.part = part
                    self.onBehalfOfContentOwner = onBehalfOfContentOwner
                }
            }

            public var options: Options

            public var body: Channel?

            public init(body: Channel?, options: Options, encoder: RequestEncoder? = nil) {
                self.body = body
                self.options = options
                super.init(service: YoutubeChannelsUpdate.service) { defaultEncoder in
                    return try (encoder ?? defaultEncoder).encode(body)
                }
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(dollarXgafv: Xgafv? = nil, accessToken: String? = nil, alt: Alt? = nil, callback: String? = nil, fields: String? = nil, key: String? = nil, oauthToken: String? = nil, prettyPrint: Bool? = nil, quotaUser: String? = nil, uploadProtocol: String? = nil, uploadType: String? = nil, part: [String], onBehalfOfContentOwner: String? = nil, body: Channel? = nil) {
                let options = Options(dollarXgafv: dollarXgafv, accessToken: accessToken, alt: alt, callback: callback, fields: fields, key: key, oauthToken: oauthToken, prettyPrint: prettyPrint, quotaUser: quotaUser, uploadProtocol: uploadProtocol, uploadType: uploadType, part: part, onBehalfOfContentOwner: onBehalfOfContentOwner)
                self.init(body: body, options: options)
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let dollarXgafv = options.dollarXgafv?.encode() {
                  params["$.xgafv"] = dollarXgafv
                }
                if let accessToken = options.accessToken {
                  params["access_token"] = accessToken
                }
                if let alt = options.alt?.encode() {
                  params["alt"] = alt
                }
                if let callback = options.callback {
                  params["callback"] = callback
                }
                if let fields = options.fields {
                  params["fields"] = fields
                }
                if let key = options.key {
                  params["key"] = key
                }
                if let oauthToken = options.oauthToken {
                  params["oauth_token"] = oauthToken
                }
                if let prettyPrint = options.prettyPrint {
                  params["prettyPrint"] = prettyPrint
                }
                if let quotaUser = options.quotaUser {
                  params["quotaUser"] = quotaUser
                }
                if let uploadProtocol = options.uploadProtocol {
                  params["upload_protocol"] = uploadProtocol
                }
                if let uploadType = options.uploadType {
                  params["uploadType"] = uploadType
                }
                params["part"] = options.part.joined(separator: ",")
                if let onBehalfOfContentOwner = options.onBehalfOfContentOwner {
                  params["onBehalfOfContentOwner"] = onBehalfOfContentOwner
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = Channel

            /** Successful response */
            case status200(Channel)

            public var success: Channel? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(Channel.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
